//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationConferention
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizers
    {
        public int ID_Organizator { get; set; }
        public string FIO { get; set; }
        public int Gendre { get; set; }
        public string Email { get; set; }
        public System.DateTime DateBirthday { get; set; }
        public int Country { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Gendre Gendre1 { get; set; }
    }
}
