//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationConferention
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanEvent()
        {
            this.ShortInformation = new HashSet<ShortInformation>();
        }
    
        public int ID_Event { get; set; }
        public string Event { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public int City { get; set; }
    
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation { get; set; }
    }
}
