//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationConferention
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortInformation
    {
        public int ID_Information { get; set; }
        public int EventNumber { get; set; }
        public int EventsName { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public int Activity { get; set; }
        public int Day { get; set; }
        public string TimeStart { get; set; }
        public int Moderator { get; set; }
        public Nullable<int> Jury1 { get; set; }
        public Nullable<int> Jury2 { get; set; }
        public Nullable<int> Jury3 { get; set; }
        public Nullable<int> Jury4 { get; set; }
        public Nullable<int> Jury5 { get; set; }
        public Nullable<int> Winner { get; set; }
    
        public virtual Activity Activity1 { get; set; }
        public virtual PlanEvent PlanEvent { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Users Users3 { get; set; }
        public virtual Users Users4 { get; set; }
        public virtual Users Users5 { get; set; }
        public virtual Users Users6 { get; set; }
    }
}
