//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganisationConferention
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.ShortInformation = new HashSet<ShortInformation>();
            this.ShortInformation1 = new HashSet<ShortInformation>();
            this.ShortInformation2 = new HashSet<ShortInformation>();
            this.ShortInformation3 = new HashSet<ShortInformation>();
            this.ShortInformation4 = new HashSet<ShortInformation>();
            this.ShortInformation5 = new HashSet<ShortInformation>();
            this.ShortInformation6 = new HashSet<ShortInformation>();
        }
    
        public int ID_Users { get; set; }
        public string FIO { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public System.DateTime DateBirthday { get; set; }
        public int Country { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Direction { get; set; }
        public Nullable<int> Events { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public int Role { get; set; }
        public byte[] UserPhoto { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Direction Direction1 { get; set; }
        public virtual Events Events1 { get; set; }
        public virtual Gendre Gendre { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShortInformation> ShortInformation6 { get; set; }
    }
}
